refactoring
lean-delivery/ansible-role-jenkins-slave pull request #16
Opened 2019-10-02 14:44 UTC by pavelpikta

* fixed tests
* updated role from ADK

2019-10-10 06:04 UTC, ViachaslauKabak approved these changes

2019-10-11 12:02 UTC, tgadiev approved these changes

2019-10-11 12:02 UTC, tgadiev commented on meta/main.yml
>      - "jenkins"
```suggestion
    - "jenkins"
    - "windows"
    - "slave"
```

2019-10-11 12:21 UTC, tgadiev requested changes

2019-10-11 12:21 UTC, tgadiev commented on .gitlab-ci.yml
> +.EPC jenkins-slave:
```suggestion
EPC jenkins-slave:
```

2019-10-11 14:18 UTC, merged